import type { FishSpecies } from "./types.ts";

export const FISH: FishSpecies[] = [
  {
    id: "golden-shiner",
    name: "Golden shiner",
    minWeight: 0.1,
    maxWeight: 0.4,
    minStrength: 1,
    minAccuracy: 1,
    challenge: "mash",
    spots: ["dock", "reeds"],
    basePoints: 7,
    rarity: "common",
    color: "#d4a84b",
    accent: "#f0d78a",
  },
  {
    id: "bluegill",
    name: "Bluegill",
    minWeight: 0.1,
    maxWeight: 0.6,
    minStrength: 1,
    minAccuracy: 1,
    challenge: "mash",
    spots: ["point"],
    basePoints: 8,
    rarity: "common",
    color: "#3d6b4f",
    accent: "#e8c45c",
  },
  {
    id: "perch",
    name: "Yellow perch",
    minWeight: 0.3,
    maxWeight: 1.2,
    minStrength: 1,
    minAccuracy: 1,
    challenge: "mash",
    spots: ["dock", "reeds", "dropoff"],
    basePoints: 12,
    rarity: "common",
    color: "#c9a13a",
    accent: "#5a3d1c",
  },
  {
    id: "brook-trout",
    name: "Brook trout",
    minWeight: 0.5,
    maxWeight: 2,
    minStrength: 2,
    minAccuracy: 1,
    challenge: "timing",
    spots: ["reeds", "point"],
    basePoints: 22,
    rarity: "uncommon",
    color: "#8b3a2a",
    accent: "#e8c9a0",
  },
  {
    id: "smallmouth-bass",
    name: "Smallmouth bass",
    minWeight: 1,
    maxWeight: 4,
    minStrength: 2,
    minAccuracy: 1,
    challenge: "timing",
    spots: ["dock", "dropoff"],
    basePoints: 26,
    rarity: "uncommon",
    color: "#5c4a38",
    accent: "#c4a574",
  },
  {
    id: "rainbow-trout",
    name: "Rainbow trout",
    minWeight: 1,
    maxWeight: 4,
    minStrength: 2,
    minAccuracy: 1,
    challenge: "timing",
    spots: ["reeds", "dropoff"],
    basePoints: 28,
    rarity: "uncommon",
    color: "#c47a6a",
    accent: "#7eb8a8",
  },
  {
    id: "carp",
    name: "Common carp",
    minWeight: 4,
    maxWeight: 18,
    minStrength: 3,
    minAccuracy: 1,
    challenge: "tension",
    spots: ["dock", "reeds"],
    basePoints: 36,
    rarity: "uncommon",
    color: "#b57a4a",
    accent: "#e8c9a0",
  },
  {
    id: "pike",
    name: "Northern pike",
    minWeight: 3,
    maxWeight: 15,
    minStrength: 4,
    minAccuracy: 1,
    challenge: "tension",
    spots: ["reeds", "dropoff", "point"],
    basePoints: 48,
    rarity: "rare",
    color: "#4a6b48",
    accent: "#c9d4a8",
  },
  {
    id: "catfish",
    name: "Channel catfish",
    minWeight: 2,
    maxWeight: 12,
    minStrength: 3,
    minAccuracy: 1,
    challenge: "sequence",
    spots: ["dock", "dropoff"],
    basePoints: 40,
    rarity: "uncommon",
    color: "#4a453c",
    accent: "#c4b89a",
  },
  {
    id: "burbot",
    name: "Burbot",
    minWeight: 1.5,
    maxWeight: 8,
    minStrength: 3,
    minAccuracy: 2,
    challenge: "sequence",
    spots: ["dropoff"],
    basePoints: 52,
    rarity: "rare",
    color: "#3d4a52",
    accent: "#8aa0a8",
  },
  {
    id: "salmon",
    name: "Landlocked salmon",
    minWeight: 2,
    maxWeight: 8,
    minStrength: 4,
    minAccuracy: 1,
    challenge: "sequence",
    spots: ["dropoff"],
    basePoints: 55,
    rarity: "rare",
    color: "#c45c4a",
    accent: "#e8c4b0",
  },
  {
    id: "tiger-muskie",
    name: "Tiger muskie",
    minWeight: 10,
    maxWeight: 35,
    minStrength: 5,
    minAccuracy: 2,
    challenge: "surge",
    spots: ["reeds"],
    basePoints: 100,
    rarity: "legendary",
    color: "#6b8f3a",
    accent: "#2a2e24",
  },
  {
    id: "sturgeon",
    name: "Lake sturgeon",
    minWeight: 20,
    maxWeight: 80,
    minStrength: 5,
    minAccuracy: 3,
    challenge: "surge",
    spots: ["dropoff"],
    basePoints: 120,
    rarity: "legendary",
    color: "#6a7a78",
    accent: "#c5b89a",
  },
];

export function fishById(id: string): FishSpecies | undefined {
  return FISH.find((fish) => fish.id === id);
}
