import type { FishSpecies } from "./types.ts";

export const FISH: FishSpecies[] = [
  {
    id: "bluegill",
    name: "Bluegill",
    minWeight: 0.1,
    maxWeight: 0.6,
    minStrength: 1,
    minAccuracy: 1,
    challenge: "mash",
    spots: ["dock"],
    basePoints: 8,
    rarity: "common",
  },
  {
    id: "perch",
    name: "Yellow perch",
    minWeight: 0.3,
    maxWeight: 1.2,
    minStrength: 1,
    minAccuracy: 1,
    challenge: "mash",
    spots: ["dock", "reeds"],
    basePoints: 12,
    rarity: "common",
  },
  {
    id: "brook-trout",
    name: "Brook trout",
    minWeight: 0.5,
    maxWeight: 2,
    minStrength: 2,
    minAccuracy: 1,
    challenge: "timing",
    spots: ["reeds"],
    basePoints: 22,
    rarity: "uncommon",
  },
  {
    id: "rainbow-trout",
    name: "Rainbow trout",
    minWeight: 1,
    maxWeight: 4,
    minStrength: 2,
    minAccuracy: 1,
    challenge: "timing",
    spots: ["reeds", "dropoff"],
    basePoints: 28,
    rarity: "uncommon",
  },
  {
    id: "carp",
    name: "Common carp",
    minWeight: 4,
    maxWeight: 18,
    minStrength: 3,
    minAccuracy: 1,
    challenge: "tension",
    spots: ["dock", "reeds"],
    basePoints: 36,
    rarity: "uncommon",
  },
  {
    id: "pike",
    name: "Northern pike",
    minWeight: 3,
    maxWeight: 15,
    minStrength: 4,
    minAccuracy: 1,
    challenge: "tension",
    spots: ["reeds", "dropoff"],
    basePoints: 48,
    rarity: "rare",
  },
  {
    id: "catfish",
    name: "Channel catfish",
    minWeight: 2,
    maxWeight: 12,
    minStrength: 3,
    minAccuracy: 1,
    challenge: "sequence",
    spots: ["dock", "dropoff"],
    basePoints: 40,
    rarity: "uncommon",
  },
  {
    id: "salmon",
    name: "Landlocked salmon",
    minWeight: 2,
    maxWeight: 8,
    minStrength: 4,
    minAccuracy: 1,
    challenge: "sequence",
    spots: ["dropoff"],
    basePoints: 55,
    rarity: "rare",
  },
  {
    id: "sturgeon",
    name: "Lake sturgeon",
    minWeight: 20,
    maxWeight: 80,
    minStrength: 5,
    minAccuracy: 3,
    challenge: "surge",
    spots: ["dropoff"],
    basePoints: 120,
    rarity: "legendary",
  },
];

export function fishById(id: string): FishSpecies | undefined {
  return FISH.find((fish) => fish.id === id);
}
